name: Publish GitHub Actions Artifacts test

on:
  push:
    branches: [main]

jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: dqx_dat_dump
          repository: KodywithaK/dqx_dat_dump
          ref: main
      - uses: actions/checkout@v4
        with:
          # path: test
          repository: KodywithaK/dqx-offline-localization
          ref: testing
          sparse-checkout: |
            FINAL/pakchunk0-Switch_P/Holiday/Content/NonAssets/ETP/
          # sparse-checkout-cone-mode: false
          # FINAL/pakchunk0-Switch_P/Holiday/Content/NonAssets/ETP/eventTextCsA11Client.win32.json
      - run: ls

      - name: Add downloads & list.txt
        run: |
          mkdir downloads
          printf '%s\n' * > downloads/list.txt
          cd downloads
          echo '1' > 1.txt
          echo '2' > 2.txt
          cd ..

      - name: Get Current Time
        run: |
          echo "time=$(date +'%Y_%m_%d')" >> $GITHUB_ENV

      - name: Upload Artifact GitHub Action
        uses: actions/upload-artifact@main
        with:
          name: assets_${{ env.time }}
          path: |
            downloads
          retention-days: 3
