name: Publish GitHub Actions Artifacts test

on:
  push:
    branches: [main]

jobs:
  archive-build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - temp download folder
        run: mkdir downloads

      - name: Step 2 - add artifacts to publish to temp folder
        run: |
          cd downloads
          echo '1' > 1.txt
          echo '2' > 2.txt
          cd ..

      - name: Step 3 - Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with:
          name: assets
          path: downloads
