name: Publish GitHub Actions Artifacts

on:
  workflow_dispatch:
  # push:
    # branches: [main]
    # paths:
    #   - 'FINAL/pakchunk0-Switch_P/Holiday/Content/NonAssets/ETP/**'

jobs:
  archive-build-artifacts:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - name: Checkout dqx_dat_dump
        uses: actions/checkout@v4
        with:
          path: ./dqx_dat_dump
          # repository: dqx-translation-project/dqx_dat_dump
          repository: KodywithaK/dqx_dat_dump
          # ref: main
          # ref: test

      - name: Checkout dqx-offline-localization
        uses: actions/checkout@v4
        with:
          path: ./dqx-offline-localization
          repository: KodywithaK/dqx-offline-localization
          ref: testing
          sparse-checkout: |
            FINAL/pakchunk0-Switch_P/Holiday/Content/NonAssets/ETP/
          # FINAL/pakchunk0-Switch_P/Holiday/Content/NonAssets/ETP/eventTextCsA11Client.win32.json
          # sparse-checkout-cone-mode: false
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          architecture: 'x64'
          # python-version: '3.x'
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies
      - name: Run Python         
        run: |
          cd ./dqx_dat_dump/
          python -m venv venv
          source ./venv/bin/activate
          pip install -r requirements.txt
          cd ./tools/packing/
          python ./pack_etp_GitHubActions.py -a
          deactivate
          cd ~
          ./UnrealEngine-4.27/Engine/Binaries/Linux/UnrealPak ../../../../actions-runner/_work/test/test/downloads/pakchunk0-WindowsNoEditor_Dialog_Latest_PC_P.pak -Create=../../../../dqx_dat_dump/tools/packing/responsefile_PC.txt
          ./UnrealEngine-4.27/Engine/Binaries/Linux/UnrealPak ../../../../actions-runner/_work/test/test/downloads/pakchunk0-Switch_Dialog_Latest_P.pak -Create=../../../../dqx_dat_dump/tools/packing/responsefile_Switch.txt
        # <UnrealPak Filepath>/UnrealPak     <UnrealPak Filepath Reversed>/downloads/pakchunk0-Switch_GitHubActions_Latest_P.pak -Create=<UnrealPak Filepath Reversed>/dqx_dat_dump/tools/packing/responsefile.txt
        # ./UnrealEngine-4.27/Engine/Binaries/Linux/UnrealPak ../../../../downloads/pakchunk0-Switch_GitHubActions_Latest_P.pak -Create=../../../../dqx_dat_dump/tools/packing/responsefile_Switch.txt          
          
        # run: python -c 'import os, sys; print(sys.version); path = "."; dirs = os.listdir(path)'

      # - name: Add downloads & list.txt
        # run: |
          # ls -R
        # run: |
        #   mkdir downloads
        #   printf '%s\n' * > downloads/list.txt
        #   cd downloads
        #   echo '1' > 1.txt
        #   echo '2' > 2.txt
        #   cd ..
      # - name: Add downloads & list.txt
      #   run: |
      #     if exist downloads rd /s /q downloads
      #     mkdir downloads
      #     cd downloads
      #     echo '1' > 1.txt

      - name: Get Current Time
        run: |
          echo "time=$(date +'%Y_%m_%d_%H%M')" >> $GITHUB_ENV

      - name: Upload Artifact GitHub Action
        uses: actions/upload-artifact@v4
        with:
          name: GitHubActions_Latest_Dialog_${{ env.time }}
          # path: |
          path: |
            downloads
          # ./dqx_dat_dump/tools/packing/new_etp
          retention-days: 1

# Error 0x80070781: The name of the file cannot be resolved by the system.
# System.Threading.Tasks.Dataflow.dll
# System.Web.WebPages.Deployment.dll
