on: [push, workflow_dispatch]

jobs:
  create_release:
    permissions: write-all
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - name: echo
        id: echo
        run: |
          # echo -e "\033[0;31m"
          # echo -e "\033[0;32m"
          # echo -e "\033[0;33m"
          echo -e "\033[0;31m Error"
          echo -e "\033[0;32m Success"
          echo -e "\033[0;33m Warning"

      - run: |
          mkdir -p ./downloads
          echo hello > ./downloads/world.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ./downloads/world.txt

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: ./downloads
      - run: ls -R ./downloads

      - name: Create Release
        run: |
          echo -e "GITHUB_REF =\n\t\033[0;32m${GITHUB_REF}"
          echo -e "GITHUB_REF#refs/*/ =\n\t\033[0;32m${GITHUB_REF#refs/*/}"
          echo -e "GITHUB_REF_NAME =\n\t\033[0;32m${GITHUB_REF_NAME}"
          gh release upload latest ./downloads/* --clobber
