on: [push, workflow_dispatch]

env: 
  Error: "\033[0;31mError: "
  Success: "\033[0;32mSuccess: "
  Warning: "\033[0;33mWarning: "

jobs:
  create_release:
    permissions: write-all
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - name: echo
        id: echo
        run: |
          # echo -e "\033[0;31m"
          # echo -e "\033[0;32m"
          # echo -e "\033[0;33m"
          echo -e "${Error}  Error"
          echo -e "${Success}  Success"
          echo -e "${Warning}  Warning"

      - name: Create Release
        run: |
          echo -e "\033[0;33msteps.echo.outputs = ${{ steps.echo.outputs }}"
          echo -e "\033[0;33msteps.echo.conclusion = ${{ steps.echo.conclusion }}"
          echo -e "\033[0;33msteps.echo.outcome = ${{ steps.echo.outcome }}"
          echo -e "GITHUB_REF =\n\t\033[0;32m${GITHUB_REF}"
          echo -e "GITHUB_REF#refs/*/ =\n\t\033[0;32m${GITHUB_REF#refs/*/}"
          echo -e "GITHUB_REF_NAME =\n\t\033[0;32m${GITHUB_REF_NAME}"
          # gh release upload latestTest README.md --clobber
