on: [push, workflow_dispatch]

jobs:
  create_release:
    permissions: write-all
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - name: echo
        id: echo
        run: |
          # echo -e "\033[0;31m"
          # echo -e "\033[0;32m"
          # echo -e "\033[0;33m"
          echo -e "\033[0;31m Error"
          echo -e "\033[0;32m Success"
          echo -e "\033[0;33m Warning"

      - run: |
          mkdir -p ./downloads
          echo hello > ./downloads/world.txt

      - name: Get Current Time
        run: |
          echo "time=$(date +'%Y_%m_%d_%H%M')" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GitHubActions_Dialog_Latest_${{ env.time }}
          path: ./downloads/*

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: ./downloads
      - run: ls -R ./downloads/GitHubActions_Dialog_Latest_*

      - name: Create Release
        run: |
          echo -e "GITHUB_REF =\n\t\033[0;32m${GITHUB_REF}"
          echo -e "GITHUB_REF#refs/*/ =\n\t\033[0;32m${GITHUB_REF#refs/*/}"
          echo -e "GITHUB_REF_NAME =\n\t\033[0;32m${GITHUB_REF_NAME}"
          gh release delete latest -y
          gh release create latest ./downloads/GitHubActions_Dialog_Latest_*/* -p -F changelog.md

          # gh release upload latest ./downloads/GitHubActions_Dialog_Latest_*/* --clobber
          # gh release upload latest ./downloads/GitHubActions_Dialog_Latest_*/*
