on: [push, workflow_dispatch]

jobs:
    create_release:
        permissions: write-all
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@main
            - name: Build Artifacts
              run: ./release.sh

            - name: Create Release
              run: |
                  echo -e "GITHUB_REF =\n\t\033[0;32m${GITHUB_REF}"
                  echo -e "GITHUB_REF#refs/*/ =\n\t\033[0;32m${GITHUB_REF#refs/*/}"
                  echo -e "GITHUB_REF_NAME =\n\t\033[0;32m${GITHUB_REF_NAME}"
                  gh release upload latestTest README.md --clobber
