on: [push, workflow_dispatch]

jobs:
  create_release:
    permissions: write-all
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - name: echo
        id: echo
        run: |
          echo -e "\033[0;31mRed"
          echo -e "\033[0;32mGreen"
          echo -e "\033[0;33mYellow"
          echo -e "\033[0;34mtest"
          echo -e "\033[0;35mtest"
          echo -e "\033[0;36mtest"
          echo -e "\033[0;37mtest"
          echo -e "\033[0;38mtest"
          echo -e "\033[0;39mtest"
          echo -e "\033[0;40mtest"
          echo -e "\033[0;41mtest"
          echo -e "\033[0;42mtest"
          echo -e "\033[0;43mtest"
          echo -e "\033[0;44mtest"
          echo -e "\033[0;45mtest"
          echo -e "\033[0;46mtest"
          echo -e "\033[0;47mtest"
          echo -e "\033[0;48mtest"
          echo -e "\033[0;49mtest"
          echo -e "\033[0;50mtest"
      - name: Create Release
        run: |
          echo -e "\034[0;33msteps.echo.outputs = ${{ steps.echo.outputs }}"
          echo -e "\034[0;33msteps.echo.conclusion = ${{ steps.echo.conclusion }}"
          echo -e "\034[0;33msteps.echo.outcome = ${{ steps.echo.outcome }}"
          echo -e "GITHUB_REF =\n\t\033[0;32m${GITHUB_REF}"
          echo -e "GITHUB_REF#refs/*/ =\n\t\033[0;32m${GITHUB_REF#refs/*/}"
          echo -e "GITHUB_REF_NAME =\n\t\033[0;32m${GITHUB_REF_NAME}"
          # gh release upload latestTest README.md --clobber
