on: [push, workflow_dispatch]

jobs:
  archive-build-artifacts:
    permissions: write-all
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@main
      - name: echo
        id: echo
        run: |
          echo -e "\033[0;31m Error"
          echo -e "\033[0;32m Success"
          echo -e "\033[0;33m Warning"

  create_release:
    needs: archive-build-artifacts
    permissions: write-all
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@main
      - name: echo
        id: echo
        run: |
          echo -e "\033[0;31m Error"
          echo -e "\033[0;32m Success"
          echo -e "\033[0;33m Warning"

          echo -e "github.workspace = \033[0;32m ${{ github.workspace }}"
          echo -e "runner.workspace = \033[0;32m ${{ runner.workspace }}"

      - name: Checkout UnrealPak
        uses: actions/checkout@v4
        with:
          path: ./UnrealPak
          repository: KodywithaK/UnrealPak
          sparse-checkout: Linux

      - run: |
          mkdir -p ./downloads
          echo hello > ./downloads/world.txt
          ${{ github.workspace }}/UnrealPak/UnrealPak ${{ github.workspace }}/downloads/pakchunk0-WindowsNoEditor_English_Dialogue_Latest_P.pak

      - name: Get Current Time
        run: |
          echo "time=$(date +'%Y_%m_%d_%H%M')" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GitHubActions_Dialog_Latest_${{ env.time }}
          path: ./downloads/*

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: ./downloads
      - run: |
          ls ./downloads/GitHubActions_Dialog_Latest_*

      - name: Create Release
        run: |
          echo -e "GITHUB_REF =\n\t\033[0;32m${GITHUB_REF}"
          echo -e "GITHUB_REF#refs/*/ =\n\t\033[0;32m${GITHUB_REF#refs/*/}"
          echo -e "GITHUB_REF_NAME =\n\t\033[0;32m${GITHUB_REF_NAME}"
          gh release delete latest -y
          gh release create latest ./downloads/GitHubActions_Dialog_Latest_*/* -p --generate-notes